language: ruby
cache: bundler
sudo: false

rvm:
  - 2.3.3
  - 2.4.1

branches:
  only:
    - master

before_script:
  - git clone https://github.com/vmware/vsphere-automation-sdk-ruby.git
  - cd vsphere-automation-sdk-ruby
  - gem build vsphere-automation-sdk-ruby.gemspec
  - gem install pkg/*.gem

script:
  - bundle exec rake style
  - bundle exec rake spec
